import screenpy_selenium


def test_screenpy_selenium():
    expected = (
        "AcceptAlert",
        "Attribute",
        "BrowseTheWeb",
        "BrowserTitle",
        "BrowserURL",
        "BrowsingError",
        "Chain",
        "Chainable",
        "Clear",
        "Click",
        "Clickable",
        "ContextClick",
        "Cookies",
        "DismissAlert",
        "Displayed",
        "DoubleClick",
        "Element",
        "Enabled",
        "Enter",
        "Enter2FAToken",
        "Exist",
        "Exists",
        "GoBack",
        "GoForward",
        "HoldDown",
        "Hover",
        "Invisible",
        "IsClickable",
        "IsDisplayed",
        "IsEnabled",
        "IsInvisible",
        "IsNotDisplayed",
        "IsPresent",
        "IsVisible",
        "List",
        "MoveMouse",
        "NotDisplayed",
        "Number",
        "Open",
        "Pause",
        "Pauses",
        "Present",
        "Press",
        "Refresh",
        "RefreshPage",
        "Release",
        "Reload",
        "ReloadPage",
        "RespondToPrompt",
        "RespondToThePrompt",
        "RightClick",
        "SaveConsoleLog",
        "SaveScreenshot",
        "Select",
        "SelectByIndex",
        "SelectByText",
        "SelectByValue",
        "Selected",
        "SwitchTo",
        "SwitchToTab",
        "SwitchToWindow",
        "TakeScreenshot",
        "Target",
        "TargetingError",
        "Text",
        "TextOfTheAlert",
        "TheAttribute",
        "TheBrowserTitle",
        "TheBrowserURL",
        "TheCookies",
        "TheElement",
        "TheList",
        "TheNumber",
        "TheSelected",
        "TheText",
        "TheTextOfTheAlert",
        "Visible",
        "Visit",
        "Wait",
    )

    assert sorted(screenpy_selenium.__all__) == sorted(expected)
    return


def test_abilities():
    expected = ("BrowseTheWeb",)
    assert sorted(screenpy_selenium.abilities.__all__) == sorted(expected)


def test_actions():
    expected = (
        "AcceptAlert",
        "Chain",
        "Clear",
        "Click",
        "ContextClick",
        "DismissAlert",
        "DoubleClick",
        "Enter",
        "Enter2FAToken",
        "GoBack",
        "GoForward",
        "HoldDown",
        "Hover",
        "MoveMouse",
        "Open",
        "Pause",
        "Pauses",
        "Press",
        "Refresh",
        "RefreshPage",
        "Release",
        "Reload",
        "ReloadPage",
        "RespondToPrompt",
        "RespondToThePrompt",
        "RightClick",
        "SaveConsoleLog",
        "SaveScreenshot",
        "Select",
        "SelectByIndex",
        "SelectByText",
        "SelectByValue",
        "SwitchTo",
        "SwitchToTab",
        "SwitchToWindow",
        "TakeScreenshot",
        "Visit",
        "Wait",
    )
    assert sorted(screenpy_selenium.actions.__all__) == sorted(expected)


def test_questions():
    expected = [
        "Attribute",
        "BrowserTitle",
        "BrowserURL",
        "Cookies",
        "Element",
        "List",
        "Number",
        "Selected",
        "Text",
        "TextOfTheAlert",
        "TheAttribute",
        "TheBrowserTitle",
        "TheBrowserURL",
        "TheCookies",
        "TheElement",
        "TheList",
        "TheNumber",
        "TheSelected",
        "TheText",
        "TheTextOfTheAlert",
    ]
    assert all(item in screenpy_selenium.questions.__all__ for item in expected)


def test_resolutions():
    expected = [
        "Clickable",
        "Displayed",
        "Enabled",
        "Exist",
        "Exists",
        "Invisible",
        "IsClickable",
        "IsDisplayed",
        "IsEnabled",
        "IsInvisible",
        "IsNotDisplayed",
        "IsPresent",
        "IsVisible",
        "NotDisplayed",
        "Present",
        "Visible",
    ]
    assert sorted(screenpy_selenium.resolutions.__all__) == sorted(expected)
