from __future__ import annotations

import screenpy_selenium


def test_screenpy_selenium() -> None:
    expected = (
        "AcceptAlert",
        "AcceptsAlert",
        "Attribute",
        "BrowserTitle",
        "BrowserURL",
        "BrowseTheWeb",
        "BrowsingError",
        "Chain",
        "Chainable",
        "Chains",
        "Clear",
        "Clears",
        "Click",
        "Clickable",
        "Clicks",
        "ContextClick",
        "ContextClicks",
        "Cookies",
        "Disabled",
        "DismissAlert",
        "DismissesAlert",
        "Displayed",
        "DoubleClick",
        "DoubleClicks",
        "Element",
        "Enabled",
        "Enter",
        "Enter2FAToken",
        "Enters",
        "Enters2FAToken",
        "Exist",
        "Exists",
        "GoBack",
        "GoesBack",
        "GoesForward",
        "GoForward",
        "HoldDown",
        "HoldsDown",
        "Hover",
        "Hovers",
        "Invisible",
        "IsClickable",
        "IsDisabled",
        "IsDisplayed",
        "IsEnabled",
        "IsInvisible",
        "IsNotDisplayed",
        "IsPresent",
        "IsVisible",
        "List",
        "MoveMouse",
        "MovesMouse",
        "NotDisplayed",
        "Number",
        "Open",
        "Opens",
        "Pause",
        "Pauses",
        "Present",
        "Press",
        "Presses",
        "Refresh",
        "Refreshes",
        "RefreshesPage",
        "RefreshPage",
        "Release",
        "Releases",
        "Reload",
        "ReloadPage",
        "Reloads",
        "ReloadsPage",
        "RespondsToPrompt",
        "RespondsToThePrompt",
        "RespondToPrompt",
        "RespondToThePrompt",
        "RightClick",
        "RightClicks",
        "SaveConsoleLog",
        "SavesConsoleLog",
        "SaveScreenshot",
        "SavesScreenshot",
        "Select",
        "SelectByIndex",
        "SelectByText",
        "SelectByValue",
        "Selected",
        "Selects",
        "SelectsByIndex",
        "SelectsByText",
        "SelectsByValue",
        "SwitchesTo",
        "SwitchesToTab",
        "SwitchesToWindow",
        "SwitchTo",
        "SwitchToTab",
        "SwitchToWindow",
        "TakeScreenshot",
        "TakesScreenshot",
        "Target",
        "TargetingError",
        "Text",
        "TextOfTheAlert",
        "TheAttribute",
        "TheBrowserTitle",
        "TheBrowserURL",
        "TheCookies",
        "TheElement",
        "TheList",
        "TheNumber",
        "TheSelected",
        "TheText",
        "TheTextOfTheAlert",
        "Visible",
        "Visit",
        "Visits",
        "Wait",
        "Waits",
        "settings",
    )

    assert sorted(screenpy_selenium.__all__) == sorted(expected)
    return


def test_abilities() -> None:
    expected = ("BrowseTheWeb",)
    assert sorted(screenpy_selenium.abilities.__all__) == sorted(expected)


def test_actions() -> None:
    expected = (
        "AcceptAlert",
        "AcceptsAlert",
        "Chain",
        "Chains",
        "Clear",
        "Clears",
        "Click",
        "Clicks",
        "ContextClick",
        "ContextClicks",
        "DismissAlert",
        "DismissesAlert",
        "DoubleClick",
        "DoubleClicks",
        "Enter",
        "Enter2FAToken",
        "Enters",
        "Enters2FAToken",
        "GoBack",
        "GoesBack",
        "GoesForward",
        "GoForward",
        "HoldDown",
        "HoldsDown",
        "Hover",
        "Hovers",
        "MoveMouse",
        "MovesMouse",
        "Open",
        "Opens",
        "Pause",
        "Pauses",
        "Press",
        "Presses",
        "Refresh",
        "Refreshes",
        "RefreshesPage",
        "RefreshPage",
        "Release",
        "Releases",
        "Reload",
        "ReloadPage",
        "Reloads",
        "ReloadsPage",
        "RespondsToPrompt",
        "RespondsToThePrompt",
        "RespondToPrompt",
        "RespondToThePrompt",
        "RightClick",
        "RightClicks",
        "SaveConsoleLog",
        "SavesConsoleLog",
        "SaveScreenshot",
        "SavesScreenshot",
        "Select",
        "SelectByIndex",
        "SelectByText",
        "SelectByValue",
        "Selects",
        "SelectsByIndex",
        "SelectsByText",
        "SelectsByValue",
        "SwitchesTo",
        "SwitchesToTab",
        "SwitchesToWindow",
        "SwitchTo",
        "SwitchToTab",
        "SwitchToWindow",
        "TakeScreenshot",
        "TakesScreenshot",
        "Visit",
        "Visits",
        "Wait",
        "Waits",
    )
    assert sorted(screenpy_selenium.actions.__all__) == sorted(expected)


def test_questions() -> None:
    expected = [
        "Attribute",
        "BrowserTitle",
        "BrowserURL",
        "Cookies",
        "Element",
        "List",
        "Number",
        "Selected",
        "Text",
        "TextOfTheAlert",
        "TheAttribute",
        "TheBrowserTitle",
        "TheBrowserURL",
        "TheCookies",
        "TheElement",
        "TheList",
        "TheNumber",
        "TheSelected",
        "TheText",
        "TheTextOfTheAlert",
    ]
    assert all(item in screenpy_selenium.questions.__all__ for item in expected)


def test_resolutions() -> None:
    expected = [
        "Clickable",
        "Disabled",
        "Displayed",
        "Enabled",
        "Exist",
        "Exists",
        "Invisible",
        "IsClickable",
        "IsDisabled",
        "IsDisplayed",
        "IsEnabled",
        "IsInvisible",
        "IsNotDisplayed",
        "IsPresent",
        "IsVisible",
        "NotDisplayed",
        "Present",
        "Visible",
    ]
    assert sorted(screenpy_selenium.resolutions.__all__) == sorted(expected)
