# -*- coding: utf-8 -*-

#  ░█▀▀▀█ █▀▀ █▀▀█ █▀▀ █▀▀ █▀▀▄ ░█▀▀█ █  █   ░█▀▀▀█ █▀▀ █   █▀▀ █▀▀▄  ▀  █  █ █▀▄▀█
#   ▀▀▀▄▄ █   █▄▄▀ █▀▀ █▀▀ █  █ ░█▄▄█ █▄▄█    ▀▀▀▄▄ █▀▀ █   █▀▀ █  █ ▀█▀ █  █ █ ▀ █
#  ░█▄▄▄█ ▀▀▀ ▀ ▀▀ ▀▀▀ ▀▀▀ ▀  ▀ ░█    ▄▄▄█   ░█▄▄▄█ ▀▀▀ ▀▀▀ ▀▀▀ ▀  ▀ ▀▀▀  ▀▀▀ ▀   ▀

"""
                                ScreenPy Selenium
                                                                      FADE IN:
INT. SITEPACKAGES DIRECTORY

ScreenPy Selenium is an extension for ScreenPy, enabling interaction with
Selenium.

:copyright: (c) 2022–2023, Perry Goy.
:license: MIT, see LICENSE for more details.
"""

import screenpy
from screenpy import *  # noqa

from .abilities import BrowseTheWeb
from .actions import (
    AcceptAlert,
    Chain,
    Clear,
    Click,
    ContextClick,
    DismissAlert,
    DoubleClick,
    Enter,
    Enter2FAToken,
    GoBack,
    GoForward,
    HoldDown,
    Hover,
    MoveMouse,
    Open,
    Pause,
    Press,
    Refresh,
    RefreshPage,
    Release,
    Reload,
    ReloadPage,
    RespondToPrompt,
    RespondToThePrompt,
    RightClick,
    SaveConsoleLog,
    SaveScreenshot,
    Select,
    SelectByIndex,
    SelectByText,
    SelectByValue,
    SwitchTo,
    SwitchToTab,
    SwitchToWindow,
    TakeScreenshot,
    Visit,
    Wait,
)
from .questions import (
    Attribute,
    BrowserTitle,
    BrowserURL,
    Cookies,
    Element,
    List,
    Number,
    Selected,
    Text,
    TextOfTheAlert,
    TheAttribute,
    TheBrowserTitle,
    TheBrowserURL,
    TheCookies,
    TheElement,
    TheList,
    TheNumber,
    TheSelected,
    TheText,
    TheTextOfTheAlert,
)
from .resolutions import (
    Clickable,
    Displayed,
    Enabled,
    Exist,
    Exists,
    Invisible,
    IsClickable,
    IsDisplayed,
    IsEnabled,
    IsInvisible,
    IsNotDisplayed,
    IsPresent,
    IsVisible,
    NotDisplayed,
    Present,
    Visible,
)
from .target import Target

__all__ = screenpy.__all__
__all__ += [
    "AcceptAlert",
    "Attribute",
    "BrowseTheWeb",
    "BrowserTitle",
    "BrowserURL",
    "Chain",
    "Clear",
    "Click",
    "Clickable",
    "ContextClick",
    "Cookies",
    "DismissAlert",
    "Displayed",
    "DoubleClick",
    "Element",
    "Enabled",
    "Enter",
    "Enter2FAToken",
    "Exist",
    "Exists",
    "GoBack",
    "GoForward",
    "HoldDown",
    "Hover",
    "Invisible",
    "IsClickable",
    "IsDisplayed",
    "IsEnabled",
    "IsInvisible",
    "IsNotDisplayed",
    "IsPresent",
    "IsVisible",
    "List",
    "MoveMouse",
    "NotDisplayed",
    "Number",
    "Open",
    "Pause",
    "Present",
    "Press",
    "Refresh",
    "RefreshPage",
    "Release",
    "Reload",
    "ReloadPage",
    "RespondToPrompt",
    "RespondToThePrompt",
    "RightClick",
    "SaveConsoleLog",
    "SaveScreenshot",
    "Select",
    "SelectByIndex",
    "SelectByText",
    "SelectByValue",
    "Selected",
    "SwitchTo",
    "SwitchToTab",
    "SwitchToWindow",
    "TakeScreenshot",
    "Target",
    "Text",
    "TextOfTheAlert",
    "TheAttribute",
    "TheBrowserTitle",
    "TheBrowserURL",
    "TheCookies",
    "TheElement",
    "TheList",
    "TheNumber",
    "TheSelected",
    "TheText",
    "TheTextOfTheAlert",
    "Visible",
    "Visit",
    "Wait",
]
